### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by Avanesh** [Chronophobe/Yahoo_OAuth2#1]
for get_access token request I am getting 401 response code.

**Comment by Chronophobe** [comment]
Not sure where you mean exactly. It's been a while since I've used this. Have you been able to authorize yourself when the script prompts you too?

**Comment by Avanesh** [comment]
I was able to get the code from
https://api.login.yahoo.com/oauth2/request_auth then i called the
function exchange_auth_token
and i got 401 response

On Sat, Feb 7, 2015 at 5:26 PM, Stan Janssen <notifications@github.com>
wrote:

> Not sure where you mean exactly. It's been a while since I've used this.
> Have you been able to authorize yourself when the script prompts you too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Chronophobe/Yahoo_OAuth2/issues/1#issuecomment-73361338>
> .
>



-- 
Avanesh Kumar
Indian Institute of Technology (IIT) Delhi
Mob: +919015191143
Linkedin <http://www.linkedin.com/profile/view?id=179125869&trk>

**Comment by Chronophobe** [comment]
Ah, yes. The method to retreive the refresh token obviously hadn't been tested. A few things went wrong there and I believe they are fixed now. 

Grabbed the docs, applied some patches and tested it. Let me know if you run into anything. :)

**Comment by Avanesh** [comment]
Traceback (most recent call last):
  File "tests.py", line 3, in <module>
    t=OAuth()
  File "/home/wealthpack-7/avanesh/mypack/myyahoo/yahoo_oauth2.py", line 22, in __init__
    self.exchange_auth_token(code)
  File "/home/wealthpack-7/avanesh/mypack/myyahoo/yahoo_oauth2.py", line 51, in exchange_auth_token
    json_response = json.loads(response._content.decode())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Chronophobe** [comment]
You're missing the consumer key and client secret in the initialisation of t.
You can't authorize yourself without that information.

For more info: https://developer.yahoo.com/oauth2/guide/

**Comment by Avanesh** [comment]
i have hard coded my consumer key and client secret in yahoo_aouth class

On Tue, Feb 10, 2015 at 7:26 PM, Stan Janssen <notifications@github.com>
wrote:

> You're missing the consumer key and client secret in the initialisation of
> t.
> You can't authorize yourself without that information.
>
> For more info: https://developer.yahoo.com/oauth2/guide/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Chronophobe/Yahoo_OAuth2/issues/1#issuecomment-73702344>
> .
>



-- 
Avanesh Kumar
Indian Institute of Technology (IIT) Delhi
Mob: +919015191143
Linkedin <http://www.linkedin.com/profile/view?id=179125869&trk>

**Comment by Chronophobe** [comment]
Can you post the contents of the response variable on line 50?
Everything seems to be working fine here.
